import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Calendar as CalendarComponent } from "@/components/ui/calendar";
import { Popover, PopoverContent, PopoverTrigger } from "@/components/ui/popover";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { supabase } from "@/integrations/supabase/client";
import { formatPkrAmount } from "@/utils/currency";
import { Users, CalendarIcon, Download, TrendingUp } from "lucide-react";
import { format, startOfDay, endOfDay, startOfMonth, endOfMonth } from "date-fns";
import { cn } from "@/lib/utils";
import { exportRevenueToCSV } from "@/utils/exportUtils";

export function StaffRevenueBreakdown() {
  const [selectedDate, setSelectedDate] = useState<Date>(new Date());
  const [viewMode, setViewMode] = useState<"daily" | "monthly">("daily");

  const dateRange = viewMode === "daily"
    ? { start: startOfDay(selectedDate), end: endOfDay(selectedDate) }
    : { start: startOfMonth(selectedDate), end: endOfMonth(selectedDate) };

  const { data: staffRevenue, isLoading } = useQuery({
    queryKey: ['staff-revenue-breakdown', dateRange.start.toISOString(), dateRange.end.toISOString()],
    queryFn: async () => {
      // Fetch invoices with created_by in the date range
      const { data: invoices, error } = await supabase
        .from('invoices')
        .select('amount, created_by, created_at, invoice_number, description, status')
        .eq('status', 'paid')
        .gte('created_at', dateRange.start.toISOString())
        .lte('created_at', dateRange.end.toISOString());

      if (error) throw error;

      // Group by created_by
      const staffMap = new Map<string, { total: number; count: number; invoices: any[] }>();
      const untracked = { total: 0, count: 0, invoices: [] as any[] };

      for (const inv of (invoices || [])) {
        if (inv.created_by) {
          const existing = staffMap.get(inv.created_by) || { total: 0, count: 0, invoices: [] };
          existing.total += Number(inv.amount) || 0;
          existing.count += 1;
          existing.invoices.push(inv);
          staffMap.set(inv.created_by, existing);
        } else {
          untracked.total += Number(inv.amount) || 0;
          untracked.count += 1;
          untracked.invoices.push(inv);
        }
      }

      // Fetch profile names for staff
      const staffIds = Array.from(staffMap.keys());
      let profiles: any[] = [];
      if (staffIds.length > 0) {
        const { data: profileData } = await supabase
          .from('profiles')
          .select('id, first_name, last_name, role')
          .in('id', staffIds);
        profiles = profileData || [];
      }

      const staffList = staffIds.map(id => {
        const profile = profiles.find(p => p.id === id);
        const data = staffMap.get(id)!;
        return {
          id,
          name: profile ? `${profile.first_name} ${profile.last_name}` : 'Unknown',
          role: profile?.role || 'unknown',
          total: data.total,
          count: data.count,
          invoices: data.invoices,
        };
      }).sort((a, b) => b.total - a.total);

      return { staffList, untracked, totalRevenue: (invoices || []).reduce((s, i) => s + (Number(i.amount) || 0), 0) };
    }
  });

  const maxRevenue = staffRevenue?.staffList?.[0]?.total || 1;

  const handleExport = () => {
    if (!staffRevenue) return;
    const label = viewMode === "daily"
      ? format(selectedDate, 'yyyy-MM-dd')
      : format(selectedDate, 'yyyy-MM');
    exportRevenueToCSV(staffRevenue.staffList, staffRevenue.untracked, label);
  };

  return (
    <Card className="border-t-4 border-t-emerald-500">
      <CardHeader className="pb-3">
        <div className="flex items-center justify-between flex-wrap gap-3">
          <div className="flex items-center gap-2">
            <div className="p-2 rounded-lg bg-emerald-50">
              <Users className="w-5 h-5 text-emerald-600" />
            </div>
            <div>
              <CardTitle className="text-base">Staff Revenue Breakdown</CardTitle>
              <p className="text-xs text-muted-foreground">Revenue generated by each staff member</p>
            </div>
          </div>
          <div className="flex items-center gap-2">
            <div className="flex rounded-lg border overflow-hidden">
              <button
                onClick={() => setViewMode("daily")}
                className={cn("px-3 py-1 text-xs font-medium transition-colors",
                  viewMode === "daily" ? "bg-emerald-600 text-white" : "bg-background hover:bg-muted"
                )}
              >
                Daily
              </button>
              <button
                onClick={() => setViewMode("monthly")}
                className={cn("px-3 py-1 text-xs font-medium transition-colors",
                  viewMode === "monthly" ? "bg-emerald-600 text-white" : "bg-background hover:bg-muted"
                )}
              >
                Monthly
              </button>
            </div>
            <Popover>
              <PopoverTrigger asChild>
                <Button variant="outline" size="sm" className="text-xs">
                  <CalendarIcon className="w-3.5 h-3.5 mr-1" />
                  {viewMode === "daily" ? format(selectedDate, 'MMM d, yyyy') : format(selectedDate, 'MMM yyyy')}
                </Button>
              </PopoverTrigger>
              <PopoverContent className="w-auto p-0" align="end">
                <CalendarComponent
                  mode="single"
                  selected={selectedDate}
                  onSelect={(d) => d && setSelectedDate(d)}
                />
              </PopoverContent>
            </Popover>
            <Button variant="outline" size="sm" onClick={handleExport} disabled={!staffRevenue}>
              <Download className="w-3.5 h-3.5 mr-1" />
              Export
            </Button>
          </div>
        </div>
      </CardHeader>
      <CardContent>
        {isLoading ? (
          <div className="space-y-3">
            {[1, 2, 3].map(i => (
              <div key={i} className="h-14 bg-muted/50 rounded-lg animate-pulse" />
            ))}
          </div>
        ) : !staffRevenue || (staffRevenue.staffList.length === 0 && staffRevenue.untracked.count === 0) ? (
          <div className="text-center py-8 text-muted-foreground">
            <Users className="w-10 h-10 mx-auto mb-2 opacity-50" />
            <p className="text-sm">No revenue data for this period</p>
            <p className="text-xs mt-1">Revenue tracking starts from new invoices created going forward</p>
          </div>
        ) : (
          <div className="space-y-4">
            {/* Total */}
            <div className="flex items-center justify-between p-3 rounded-lg bg-emerald-50 border border-emerald-200">
              <div className="flex items-center gap-2">
                <TrendingUp className="w-4 h-4 text-emerald-600" />
                <span className="font-semibold text-sm">Total Revenue</span>
              </div>
              <span className="font-bold text-lg text-emerald-700">{formatPkrAmount(staffRevenue.totalRevenue)}</span>
            </div>

            {/* Per-staff breakdown */}
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Staff Member</TableHead>
                  <TableHead>Role</TableHead>
                  <TableHead className="text-center">Invoices</TableHead>
                  <TableHead className="text-right">Revenue</TableHead>
                  <TableHead className="w-[120px]">Share</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {staffRevenue.staffList.map((staff) => (
                  <TableRow key={staff.id}>
                    <TableCell className="font-medium">{staff.name}</TableCell>
                    <TableCell>
                      <Badge variant="outline" className="text-xs capitalize">
                        {staff.role}
                      </Badge>
                    </TableCell>
                    <TableCell className="text-center">{staff.count}</TableCell>
                    <TableCell className="text-right font-semibold">
                      {formatPkrAmount(staff.total)}
                    </TableCell>
                    <TableCell>
                      <div className="w-full bg-muted rounded-full h-2">
                        <div
                          className="bg-emerald-500 h-2 rounded-full transition-all"
                          style={{ width: `${(staff.total / maxRevenue) * 100}%` }}
                        />
                      </div>
                    </TableCell>
                  </TableRow>
                ))}
                {staffRevenue.untracked.count > 0 && (
                  <TableRow>
                    <TableCell className="font-medium text-muted-foreground italic">Untracked (legacy)</TableCell>
                    <TableCell>
                      <Badge variant="secondary" className="text-xs">N/A</Badge>
                    </TableCell>
                    <TableCell className="text-center">{staffRevenue.untracked.count}</TableCell>
                    <TableCell className="text-right font-semibold text-muted-foreground">
                      {formatPkrAmount(staffRevenue.untracked.total)}
                    </TableCell>
                    <TableCell>
                      <div className="w-full bg-muted rounded-full h-2">
                        <div
                          className="bg-gray-400 h-2 rounded-full transition-all"
                          style={{ width: `${(staffRevenue.untracked.total / maxRevenue) * 100}%` }}
                        />
                      </div>
                    </TableCell>
                  </TableRow>
                )}
              </TableBody>
            </Table>
          </div>
        )}
      </CardContent>
    </Card>
  );
}
