-- ============ TRIGGERS ============
DROP TRIGGER IF EXISTS set_consultation_fee_trigger ON appointments;
CREATE TRIGGER set_consultation_fee_trigger BEFORE INSERT ON public.appointments FOR EACH ROW EXECUTE FUNCTION set_appointment_consultation_fee();
DROP TRIGGER IF EXISTS set_updated_at_appointments ON appointments;
CREATE TRIGGER set_updated_at_appointments BEFORE UPDATE ON public.appointments FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
DROP TRIGGER IF EXISTS trigger_auto_assign_queue_position ON appointments;
CREATE TRIGGER trigger_auto_assign_queue_position AFTER INSERT ON public.appointments FOR EACH ROW EXECUTE FUNCTION auto_assign_queue_position();
DROP TRIGGER IF EXISTS trigger_update_queue_on_completion ON appointments;
CREATE TRIGGER trigger_update_queue_on_completion AFTER UPDATE ON public.appointments FOR EACH ROW EXECUTE FUNCTION update_queue_on_completion();
DROP TRIGGER IF EXISTS update_assessment_entries_updated_at ON assessment_entries;
CREATE TRIGGER update_assessment_entries_updated_at BEFORE UPDATE ON public.assessment_entries FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
DROP TRIGGER IF EXISTS trg_beds_updated ON beds;
CREATE TRIGGER trg_beds_updated BEFORE UPDATE ON public.beds FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
DROP TRIGGER IF EXISTS update_daily_closings_updated_at ON daily_closings;
CREATE TRIGGER update_daily_closings_updated_at BEFORE UPDATE ON public.daily_closings FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
DROP TRIGGER IF EXISTS update_doctor_availability_updated_at ON doctor_availability;
CREATE TRIGGER update_doctor_availability_updated_at BEFORE UPDATE ON public.doctor_availability FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
DROP TRIGGER IF EXISTS update_doctor_daily_status_updated_at ON doctor_daily_status;
CREATE TRIGGER update_doctor_daily_status_updated_at BEFORE UPDATE ON public.doctor_daily_status FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
DROP TRIGGER IF EXISTS update_doctor_payments_updated_at ON doctor_payments;
CREATE TRIGGER update_doctor_payments_updated_at BEFORE UPDATE ON public.doctor_payments FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
DROP TRIGGER IF EXISTS set_updated_at_doctor_specific_schedules ON doctor_specific_schedules;
CREATE TRIGGER set_updated_at_doctor_specific_schedules BEFORE UPDATE ON public.doctor_specific_schedules FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
DROP TRIGGER IF EXISTS set_updated_at_doctor_working_hours ON doctor_working_hours;
CREATE TRIGGER set_updated_at_doctor_working_hours BEFORE UPDATE ON public.doctor_working_hours FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
DROP TRIGGER IF EXISTS update_emergency_expenses_updated_at ON emergency_expenses;
CREATE TRIGGER update_emergency_expenses_updated_at BEFORE UPDATE ON public.emergency_expenses FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
DROP TRIGGER IF EXISTS update_expenses_updated_at ON expenses;
CREATE TRIGGER update_expenses_updated_at BEFORE UPDATE ON public.expenses FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
DROP TRIGGER IF EXISTS update_finance_settings_updated_at ON finance_settings;
CREATE TRIGGER update_finance_settings_updated_at BEFORE UPDATE ON public.finance_settings FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
DROP TRIGGER IF EXISTS update_hospital_closing_balance_updated_at ON hospital_closing_balance;
CREATE TRIGGER update_hospital_closing_balance_updated_at BEFORE UPDATE ON public.hospital_closing_balance FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
DROP TRIGGER IF EXISTS update_hospital_services_updated_at ON hospital_services;
CREATE TRIGGER update_hospital_services_updated_at BEFORE UPDATE ON public.hospital_services FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
DROP TRIGGER IF EXISTS auto_xray_payment_trigger ON invoices;
CREATE TRIGGER auto_xray_payment_trigger BEFORE INSERT OR UPDATE ON public.invoices FOR EACH ROW EXECUTE FUNCTION auto_set_xray_paid();
DROP TRIGGER IF EXISTS trg_invoice_audit ON invoices;
CREATE TRIGGER trg_invoice_audit AFTER INSERT OR DELETE OR UPDATE ON public.invoices FOR EACH ROW EXECUTE FUNCTION log_invoice_change();
DROP TRIGGER IF EXISTS trg_sync_pathology_amounts ON invoices;
CREATE TRIGGER trg_sync_pathology_amounts AFTER UPDATE OF amount ON public.invoices FOR EACH ROW EXECUTE FUNCTION sync_pathology_amounts_from_invoice();
DROP TRIGGER IF EXISTS trg_admission_defaults ON ipd_admissions;
CREATE TRIGGER trg_admission_defaults BEFORE INSERT ON public.ipd_admissions FOR EACH ROW EXECUTE FUNCTION set_admission_defaults();
DROP TRIGGER IF EXISTS trg_ipd_admissions_updated ON ipd_admissions;
CREATE TRIGGER trg_ipd_admissions_updated BEFORE UPDATE ON public.ipd_admissions FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
DROP TRIGGER IF EXISTS trg_sync_bed_status ON ipd_admissions;
CREATE TRIGGER trg_sync_bed_status AFTER INSERT OR UPDATE ON public.ipd_admissions FOR EACH ROW EXECUTE FUNCTION sync_bed_status_on_admission();
DROP TRIGGER IF EXISTS trg_ipd_invoice_defaults ON ipd_invoices;
CREATE TRIGGER trg_ipd_invoice_defaults BEFORE INSERT ON public.ipd_invoices FOR EACH ROW EXECUTE FUNCTION set_ipd_invoice_defaults();
DROP TRIGGER IF EXISTS trg_ipd_invoices_updated ON ipd_invoices;
CREATE TRIGGER trg_ipd_invoices_updated BEFORE UPDATE ON public.ipd_invoices FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
DROP TRIGGER IF EXISTS trg_ipd_lab_orders_updated ON ipd_lab_orders;
CREATE TRIGGER trg_ipd_lab_orders_updated BEFORE UPDATE ON public.ipd_lab_orders FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
DROP TRIGGER IF EXISTS trg_ipd_med_orders_updated ON ipd_medicine_orders;
CREATE TRIGGER trg_ipd_med_orders_updated BEFORE UPDATE ON public.ipd_medicine_orders FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
DROP TRIGGER IF EXISTS trg_pathology_orders_updated_at ON lab_pathology_orders;
CREATE TRIGGER trg_pathology_orders_updated_at BEFORE UPDATE ON public.lab_pathology_orders FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
DROP TRIGGER IF EXISTS trg_lab_pathology_results_updated ON lab_pathology_report_results;
CREATE TRIGGER trg_lab_pathology_results_updated BEFORE UPDATE ON public.lab_pathology_report_results FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
DROP TRIGGER IF EXISTS trg_lab_pathology_reports_updated ON lab_pathology_reports;
CREATE TRIGGER trg_lab_pathology_reports_updated BEFORE UPDATE ON public.lab_pathology_reports FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
DROP TRIGGER IF EXISTS update_lab_stock_batches_updated_at ON lab_stock_batches;
CREATE TRIGGER update_lab_stock_batches_updated_at BEFORE UPDATE ON public.lab_stock_batches FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
DROP TRIGGER IF EXISTS update_lab_store_batches_updated_at ON lab_store_batches;
CREATE TRIGGER update_lab_store_batches_updated_at BEFORE UPDATE ON public.lab_store_batches FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
DROP TRIGGER IF EXISTS trg_lab_test_parameters_updated ON lab_test_parameters;
CREATE TRIGGER trg_lab_test_parameters_updated BEFORE UPDATE ON public.lab_test_parameters FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
DROP TRIGGER IF EXISTS trg_lab_test_types_updated ON lab_test_types;
CREATE TRIGGER trg_lab_test_types_updated BEFORE UPDATE ON public.lab_test_types FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
DROP TRIGGER IF EXISTS update_lab_tests_updated_at ON lab_tests;
CREATE TRIGGER update_lab_tests_updated_at BEFORE UPDATE ON public.lab_tests FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
DROP TRIGGER IF EXISTS update_miscellaneous_income_updated_at ON miscellaneous_income;
CREATE TRIGGER update_miscellaneous_income_updated_at BEFORE UPDATE ON public.miscellaneous_income FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
DROP TRIGGER IF EXISTS update_ot_expenses_updated_at ON ot_expenses;
CREATE TRIGGER update_ot_expenses_updated_at BEFORE UPDATE ON public.ot_expenses FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
DROP TRIGGER IF EXISTS update_ot_operations_updated_at ON ot_operations;
CREATE TRIGGER update_ot_operations_updated_at BEFORE UPDATE ON public.ot_operations FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
DROP TRIGGER IF EXISTS update_ot_rooms_updated_at ON ot_rooms;
CREATE TRIGGER update_ot_rooms_updated_at BEFORE UPDATE ON public.ot_rooms FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
DROP TRIGGER IF EXISTS update_ot_schedules_updated_at ON ot_schedules;
CREATE TRIGGER update_ot_schedules_updated_at BEFORE UPDATE ON public.ot_schedules FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
DROP TRIGGER IF EXISTS update_patient_documents_updated_at ON patient_documents;
CREATE TRIGGER update_patient_documents_updated_at BEFORE UPDATE ON public.patient_documents FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
DROP TRIGGER IF EXISTS set_patient_defaults_trigger ON patients;
CREATE TRIGGER set_patient_defaults_trigger BEFORE INSERT ON public.patients FOR EACH ROW EXECUTE FUNCTION set_patient_defaults();
DROP TRIGGER IF EXISTS update_payroll_updated_at ON payroll;
CREATE TRIGGER update_payroll_updated_at BEFORE UPDATE ON public.payroll FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
DROP TRIGGER IF EXISTS update_payroll_templates_updated_at ON payroll_templates;
CREATE TRIGGER update_payroll_templates_updated_at BEFORE UPDATE ON public.payroll_templates FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
DROP TRIGGER IF EXISTS update_pharmacy_account_updated_at ON pharmacy_account;
CREATE TRIGGER update_pharmacy_account_updated_at BEFORE UPDATE ON public.pharmacy_account FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
DROP TRIGGER IF EXISTS update_pharmacy_expenses_updated_at ON pharmacy_expenses;
CREATE TRIGGER update_pharmacy_expenses_updated_at BEFORE UPDATE ON public.pharmacy_expenses FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
DROP TRIGGER IF EXISTS update_postop_progress_entries_updated_at ON postop_progress_entries;
CREATE TRIGGER update_postop_progress_entries_updated_at BEFORE UPDATE ON public.postop_progress_entries FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
DROP TRIGGER IF EXISTS update_prescriptions_updated_at ON prescriptions;
CREATE TRIGGER update_prescriptions_updated_at BEFORE UPDATE ON public.prescriptions FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
DROP TRIGGER IF EXISTS update_profiles_updated_at ON profiles;
CREATE TRIGGER update_profiles_updated_at BEFORE UPDATE ON public.profiles FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
DROP TRIGGER IF EXISTS update_refunds_updated_at ON refunds;
CREATE TRIGGER update_refunds_updated_at BEFORE UPDATE ON public.refunds FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
DROP TRIGGER IF EXISTS update_treatment_chart_entries_updated_at ON treatment_chart_entries;
CREATE TRIGGER update_treatment_chart_entries_updated_at BEFORE UPDATE ON public.treatment_chart_entries FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
DROP TRIGGER IF EXISTS trg_wards_updated ON wards;
CREATE TRIGGER trg_wards_updated BEFORE UPDATE ON public.wards FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
DROP TRIGGER IF EXISTS auto_xray_reports_payment_trigger ON xray_reports;
CREATE TRIGGER auto_xray_reports_payment_trigger BEFORE INSERT OR UPDATE ON public.xray_reports FOR EACH ROW EXECUTE FUNCTION auto_set_xray_reports_paid();
DROP TRIGGER IF EXISTS update_xray_tests_updated_at ON xray_tests;
CREATE TRIGGER update_xray_tests_updated_at BEFORE UPDATE ON public.xray_tests FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
-- trigger count: 54
