-- ============ GRANTS + RLS ============
GRANT SELECT, INSERT, UPDATE, DELETE ON public.anesthesia_notes TO authenticated;
GRANT ALL ON public.anesthesia_notes TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.appointments TO authenticated;
GRANT ALL ON public.appointments TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.assessment_entries TO authenticated;
GRANT ALL ON public.assessment_entries TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.audit_logs TO authenticated;
GRANT ALL ON public.audit_logs TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.beds TO authenticated;
GRANT ALL ON public.beds TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.client_error_logs TO authenticated;
GRANT ALL ON public.client_error_logs TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.daily_closings TO authenticated;
GRANT ALL ON public.daily_closings TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.departments TO authenticated;
GRANT ALL ON public.departments TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.doctor_availability TO authenticated;
GRANT ALL ON public.doctor_availability TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.doctor_daily_status TO authenticated;
GRANT ALL ON public.doctor_daily_status TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.doctor_payments TO authenticated;
GRANT ALL ON public.doctor_payments TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.doctor_specific_schedules TO authenticated;
GRANT ALL ON public.doctor_specific_schedules TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.doctor_working_hours TO authenticated;
GRANT ALL ON public.doctor_working_hours TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.doctors TO authenticated;
GRANT ALL ON public.doctors TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.emergency_expenses TO authenticated;
GRANT ALL ON public.emergency_expenses TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.expenses TO authenticated;
GRANT ALL ON public.expenses TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.finance_settings TO authenticated;
GRANT ALL ON public.finance_settings TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.hospital_closing_balance TO authenticated;
GRANT ALL ON public.hospital_closing_balance TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.hospital_services TO authenticated;
GRANT ALL ON public.hospital_services TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.hospital_settings TO authenticated;
GRANT ALL ON public.hospital_settings TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.inventory_items TO authenticated;
GRANT ALL ON public.inventory_items TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.inventory_requests TO authenticated;
GRANT ALL ON public.inventory_requests TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.invoice_audit_log TO authenticated;
GRANT ALL ON public.invoice_audit_log TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.invoices TO authenticated;
GRANT ALL ON public.invoices TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.ipd_admissions TO authenticated;
GRANT ALL ON public.ipd_admissions TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.ipd_charges TO authenticated;
GRANT ALL ON public.ipd_charges TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.ipd_doctor_payments TO authenticated;
GRANT ALL ON public.ipd_doctor_payments TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.ipd_invoices TO authenticated;
GRANT ALL ON public.ipd_invoices TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.ipd_lab_orders TO authenticated;
GRANT ALL ON public.ipd_lab_orders TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.ipd_medicine_orders TO authenticated;
GRANT ALL ON public.ipd_medicine_orders TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.ipd_treatment_chart TO authenticated;
GRANT ALL ON public.ipd_treatment_chart TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.lab_inventory_items TO authenticated;
GRANT ALL ON public.lab_inventory_items TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.lab_parameter_subranges TO authenticated;
GRANT ALL ON public.lab_parameter_subranges TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.lab_pathology_order_items TO authenticated;
GRANT ALL ON public.lab_pathology_order_items TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.lab_pathology_orders TO authenticated;
GRANT ALL ON public.lab_pathology_orders TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.lab_pathology_report_results TO authenticated;
GRANT ALL ON public.lab_pathology_report_results TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.lab_pathology_report_test_types TO authenticated;
GRANT ALL ON public.lab_pathology_report_test_types TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.lab_pathology_reports TO authenticated;
GRANT ALL ON public.lab_pathology_reports TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.lab_reports TO authenticated;
GRANT ALL ON public.lab_reports TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.lab_stock_batches TO authenticated;
GRANT ALL ON public.lab_stock_batches TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.lab_stock_consumption TO authenticated;
GRANT ALL ON public.lab_stock_consumption TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.lab_stock_usage TO authenticated;
GRANT ALL ON public.lab_stock_usage TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.lab_store_batches TO authenticated;
GRANT ALL ON public.lab_store_batches TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.lab_test_consumables TO authenticated;
GRANT ALL ON public.lab_test_consumables TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.lab_test_parameters TO authenticated;
GRANT ALL ON public.lab_test_parameters TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.lab_test_types TO authenticated;
GRANT ALL ON public.lab_test_types TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.lab_tests TO authenticated;
GRANT ALL ON public.lab_tests TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.medical_records TO authenticated;
GRANT ALL ON public.medical_records TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.medicines TO authenticated;
GRANT ALL ON public.medicines TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.miscellaneous_income TO authenticated;
GRANT ALL ON public.miscellaneous_income TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.ot_expenses TO authenticated;
GRANT ALL ON public.ot_expenses TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.ot_operations TO authenticated;
GRANT ALL ON public.ot_operations TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.ot_rooms TO authenticated;
GRANT ALL ON public.ot_rooms TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.ot_schedules TO authenticated;
GRANT ALL ON public.ot_schedules TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.overtime_records TO authenticated;
GRANT ALL ON public.overtime_records TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.patient_discounts TO authenticated;
GRANT ALL ON public.patient_discounts TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.patient_documents TO authenticated;
GRANT ALL ON public.patient_documents TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.patients TO authenticated;
GRANT ALL ON public.patients TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.payroll TO authenticated;
GRANT ALL ON public.payroll TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.payroll_templates TO authenticated;
GRANT ALL ON public.payroll_templates TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.pharmacy_account TO authenticated;
GRANT ALL ON public.pharmacy_account TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.pharmacy_expenses TO authenticated;
GRANT ALL ON public.pharmacy_expenses TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.pharmacy_invoice_items TO authenticated;
GRANT ALL ON public.pharmacy_invoice_items TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.pharmacy_invoices TO authenticated;
GRANT ALL ON public.pharmacy_invoices TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.postop_progress_entries TO authenticated;
GRANT ALL ON public.postop_progress_entries TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.prescriptions TO authenticated;
GRANT ALL ON public.prescriptions TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.profiles TO authenticated;
GRANT ALL ON public.profiles TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.queue_positions TO authenticated;
GRANT ALL ON public.queue_positions TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.refunds TO authenticated;
GRANT ALL ON public.refunds TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.shifts TO authenticated;
GRANT ALL ON public.shifts TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.staff_shift_closings TO authenticated;
GRANT ALL ON public.staff_shift_closings TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.treatment_chart_entries TO authenticated;
GRANT ALL ON public.treatment_chart_entries TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.users TO authenticated;
GRANT ALL ON public.users TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.wards TO authenticated;
GRANT ALL ON public.wards TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.xray_reports TO authenticated;
GRANT ALL ON public.xray_reports TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.xray_tests TO authenticated;
GRANT ALL ON public.xray_tests TO service_role;

ALTER TABLE public.anesthesia_notes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.appointments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.assessment_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.beds ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.client_error_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.daily_closings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.departments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.doctor_availability ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.doctor_daily_status ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.doctor_payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.doctor_specific_schedules ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.doctor_working_hours ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.doctors ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.emergency_expenses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.expenses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.finance_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.hospital_closing_balance ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.hospital_services ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.hospital_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inventory_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inventory_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.invoice_audit_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.invoices ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ipd_admissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ipd_charges ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ipd_doctor_payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ipd_invoices ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ipd_lab_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ipd_medicine_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ipd_treatment_chart ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lab_inventory_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lab_parameter_subranges ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lab_pathology_order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lab_pathology_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lab_pathology_report_results ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lab_pathology_report_test_types ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lab_pathology_reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lab_reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lab_stock_batches ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lab_stock_consumption ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lab_stock_usage ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lab_store_batches ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lab_test_consumables ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lab_test_parameters ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lab_test_types ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lab_tests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.medical_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.medicines ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.miscellaneous_income ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ot_expenses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ot_operations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ot_rooms ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ot_schedules ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.overtime_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.patient_discounts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.patient_documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.patients ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payroll ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payroll_templates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pharmacy_account ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pharmacy_expenses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pharmacy_invoice_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pharmacy_invoices ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.postop_progress_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.prescriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.queue_positions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.refunds ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.shifts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.staff_shift_closings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.treatment_chart_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.wards ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.xray_reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.xray_tests ENABLE ROW LEVEL SECURITY;

-- anon grants only where an anon-visible policy exists
GRANT SELECT ON public.anesthesia_notes TO anon;
GRANT SELECT ON public.appointments TO anon;
GRANT SELECT ON public.assessment_entries TO anon;
GRANT SELECT ON public.audit_logs TO anon;
GRANT SELECT ON public.client_error_logs TO anon;
GRANT SELECT ON public.daily_closings TO anon;
GRANT SELECT ON public.departments TO anon;
GRANT SELECT ON public.doctor_availability TO anon;
GRANT SELECT ON public.doctor_daily_status TO anon;
GRANT SELECT ON public.doctor_payments TO anon;
GRANT SELECT ON public.doctor_specific_schedules TO anon;
GRANT SELECT ON public.doctor_working_hours TO anon;
GRANT SELECT ON public.doctors TO anon;
GRANT SELECT ON public.emergency_expenses TO anon;
GRANT SELECT ON public.expenses TO anon;
GRANT SELECT ON public.hospital_closing_balance TO anon;
GRANT SELECT ON public.hospital_services TO anon;
GRANT SELECT ON public.hospital_settings TO anon;
GRANT SELECT ON public.inventory_items TO anon;
GRANT SELECT ON public.inventory_requests TO anon;
GRANT SELECT ON public.invoices TO anon;
GRANT SELECT ON public.lab_inventory_items TO anon;
GRANT SELECT ON public.lab_reports TO anon;
GRANT SELECT ON public.lab_tests TO anon;
GRANT SELECT ON public.medical_records TO anon;
GRANT SELECT ON public.medicines TO anon;
GRANT SELECT ON public.miscellaneous_income TO anon;
GRANT SELECT ON public.ot_expenses TO anon;
GRANT SELECT ON public.ot_operations TO anon;
GRANT SELECT ON public.ot_rooms TO anon;
GRANT SELECT ON public.ot_schedules TO anon;
GRANT SELECT ON public.overtime_records TO anon;
GRANT SELECT ON public.patient_discounts TO anon;
GRANT SELECT ON public.patient_documents TO anon;
GRANT SELECT ON public.patients TO anon;
GRANT SELECT ON public.payroll TO anon;
GRANT SELECT ON public.payroll_templates TO anon;
GRANT SELECT ON public.pharmacy_account TO anon;
GRANT SELECT ON public.pharmacy_expenses TO anon;
GRANT SELECT ON public.pharmacy_invoice_items TO anon;
GRANT SELECT ON public.pharmacy_invoices TO anon;
GRANT SELECT ON public.prescriptions TO anon;
GRANT SELECT ON public.profiles TO anon;
GRANT SELECT ON public.refunds TO anon;
GRANT SELECT ON public.shifts TO anon;
GRANT SELECT ON public.staff_shift_closings TO anon;
GRANT SELECT ON public.treatment_chart_entries TO anon;
GRANT SELECT ON public.users TO anon;
GRANT SELECT ON public.xray_reports TO anon;
GRANT SELECT ON public.xray_tests TO anon;
