// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://notzlgtnuncyribdjzen.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5vdHpsZ3RudW5jeXJpYmRqemVuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MDIzMDYsImV4cCI6MjA2NTQ3ODMwNn0.-6vyAy86TR9W8LPkTphGUG22oteHD1SycSogyqqb5b0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});